apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: holmes
  name: oppslag-bruker-frontend
  namespace: holmes

spec:
  ingresses:
    - https://oppslag-bruker.intern.dev.nav.no
    - https://oppslag-bruker.ansatt.dev.nav.no
  accessPolicy:
    outbound:
      rules:
        - application: nav-persondata-api
          namespace: holmes
  image: {{image}}
  port: 3000
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      allowAllUsers: false
      claims:
        roups:
          - id: "b734a20d-63e3-4b44-bb77-87f7f0b7f48a" # 0000-GA-kontroll-Oppslag-Bruker-Utvidet
          - id: "222dedb1-a80d-48c9-b8d3-1e8149be9063" # 0000-GA-kontroll-Oppslag-Bruker-Basic
        extra:
          - 'NAVident'
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /api/health
        - /assets/logos/*
  env:
    - name: NEXT_PUBLIC_BASE_URL
      value: https://oppslag-bruker.intern.dev.nav.no/
    - name: NAV_PERSONDATA_API_URL
      value: http://nav-persondata-api/
    - name: NAV_PERSONDATA_API_CLUSTER
      value: dev-gcp