apiVersion: nais.io/v1alpha1
kind: Application

metadata:
  labels:
    team: holmes
  name: oppslag-bruker-frontend
  namespace: holmes

spec:
  ingresses:
    - https://oppslag-bruker.intern.dev.nav.no
    - https://oppslag-bruker.ansatt.dev.nav.no
  accessPolicy:
    outbound:
      rules:
        - application: nav-persondata-api
          namespace: holmes
  image: {{image}}
  port: 3000
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      allowAllUsers: true
      claims:
        extra:
          - 'NAVident'
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /api/health
        - /assets/logos/*
  env:
    - name: NEXT_PUBLIC_BASE_URL
      value: https://oppslag-bruker.intern.dev.nav.no/
    - name: NAV_PERSONDATA_API_URL
      value: http://nav-persondata-api/
    - name: NAV_PERSONDATA_API_CLUSTER
      value: dev-gcp