import type { Metadata } from "next";
import Script from "next/script";
import "@navikt/ds-css";
import { FeatureProvider } from "./context/FeatureContext";
import { fetchDecoratorReact } from "@navikt/nav-dekoratoren-moduler/ssr";

import "./page.module.css";
import { Page } from "@navikt/ds-react";
import HolmesHeader from "./components/header/holmesHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({
                            children,
                          }: Readonly<{ children: React.ReactNode }>) => {
  const Decorator = await fetchDecoratorReact({
    env: "prod",
  });

  return (
      <html lang="no">
      <head>
        <Decorator.HeadAssets />
      </head>
      <body>
      <Page>
          <FeatureProvider>
        <HolmesHeader/>
        {children}
          </FeatureProvider>
        <Decorator.Scripts loader={Script} />
      </Page>
      </body>
      </html>
  );
};

export default RootLayout;