name: Verifiser kodekvalitet

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  verify:
    name: Verifiser kodekvalitet
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Installer pnpm
        uses: pnpm/action-setup@3e835812ef01165f4f8ae08ade56da44427ed4e0 # v4

      - name: Sett opp Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "24"
          cache: "pnpm"
          registry-url: "https://npm.pkg.github.com"
          scope: "@navikt"

      - name: Installer avhengigheter
        run: pnpm install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: Verifiser kodekvalitet og kjør tester
        run: pnpm run verify
